	//点击按钮可以切换登录的信息
	$(".nav>li").on("click",function(){
		$(this).addClass("active").siblings().removeClass("active");
		//console.log($(this).index())
		$(".tab-pane").eq($(this).index()).addClass("active").siblings().removeClass("active");
	})
	//点击2按钮时，可以登录。
	$("#sub").click(function(){
		$.ajax({
			url:"http://localhost:1701/sign/getName",
			type:"post",
			data:{
	                user:$("#exampleInputname2").val(),
	                password:$("#exampleInputpassword2").val(),
	        },
	        success:function(data){
	        	console.log(data)
	        	if(data=="1"){
	        		location.href='url';
	        	}else if(data==0){
	        		alert("密码输入错误，请正确输入")
	        	}else{
	        		alert("用户不存在，请输入正确用户名")
	        	}
	        }
		})
	})
	//点击1按钮时，可以登录。
	$("#submit").click(function(){
		$.ajax({
			url:"http://localhost:1701/sign/getName",
			type:"post",
			data:{
	                user:$("#exampleInputName1").val(),
	                password:$("#exampleInputpassword1").val(),
	        },
	        success:function(data){
	        	console.log(data)
	        	if(data=="1"){
	        		location.href='url';
	        	}else if(data==0){
	        		alert("密码输入错误，请正确输入")
	        	}else{
	        		alert("用户不存在，请输入正确用户名")
	        	}
	        }
		})
	})

